<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.19">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Outcome regression – Causal inference (and other things)</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./03-exercises.html" rel="next">
<link href="./02-exercises.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-a3414f3ffc8cedfe87f55cc0f2c68ceb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Causal inference (and other things)</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./00-syllabus.html"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-motivation" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Motivation</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-motivation">    
        <li>
    <a class="dropdown-item" href="./01a-being-a-detective.html">
 <span class="dropdown-text">Being a detective with data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01b-why-probability-is-not-enough.html">
 <span class="dropdown-text">Why probability is not enough</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01c-clinical-trials.html">
 <span class="dropdown-text">Clinical trials as our exemplar</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01d-probability.html">
 <span class="dropdown-text">Probability gives us a formal language</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./01-exercises.html">
 <span class="dropdown-text">Exercises</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-construction" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Construction</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-construction">    
        <li>
    <a class="dropdown-item" href="./02a-assignments.html">
 <span class="dropdown-text">A list of assignments</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02b-structural-causal-models.html">
 <span class="dropdown-text">Structural causal models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02c-causal-graphs.html">
 <span class="dropdown-text">Causal graphs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02d-global-markov-property.html">
 <span class="dropdown-text">Global Markov property</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02e-potential-outcomes.html">
 <span class="dropdown-text">Potential outcomes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02f-single-world-intervention-graphs.html">
 <span class="dropdown-text">Single-world intervention graphs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./02-exercises.html">
 <span class="dropdown-text">Exercises</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-measured-confounding" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Measured confounding</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-measured-confounding">    
        <li>
    <a class="dropdown-item" href="./03a-outcome-regression.html">
 <span class="dropdown-text">Outcome regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./03-exercises.html">
 <span class="dropdown-text">Exercises</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-back-matter" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Back matter</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-back-matter">    
        <li>
    <a class="dropdown-item" href="./glossary.html">
 <span class="dropdown-text">Glossary</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./references.html">
 <span class="dropdown-text">References</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03a-outcome-regression.html">Measured confounding</a></li><li class="breadcrumb-item"><a href="./03a-outcome-regression.html"><span class="chapter-title">Outcome regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">index.html</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-syllabus.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Syllabus</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Motivation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01a-being-a-detective.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Being a detective with data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01b-why-probability-is-not-enough.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Why probability is not enough</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01c-clinical-trials.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Clinical trials as our exemplar</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01d-probability.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Probability gives us a formal language</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-exercises.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Exercises</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Construction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02a-assignments.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">A list of assignments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02b-structural-causal-models.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Structural causal models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02c-causal-graphs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Causal graphs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02d-global-markov-property.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Global Markov property</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02e-potential-outcomes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Potential outcomes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02f-single-world-intervention-graphs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Single-world intervention graphs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-exercises.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Exercises</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Measured confounding</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03a-outcome-regression.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Outcome regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-exercises.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Exercises</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Unmeasured confounding</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Sensitivity analysis</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Missing data</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Complex surveys</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Back matter</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./glossary.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Glossary</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03a-outcome-regression.html">Measured confounding</a></li><li class="breadcrumb-item"><a href="./03a-outcome-regression.html"><span class="chapter-title">Outcome regression</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Outcome regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>We now have the tools to answer our first identification question. Imagine we have an exposure <span class="math inline">\(A\)</span>, an outcome <span class="math inline">\(Y\)</span>, and a collection of common causes of <span class="math inline">\(A\)</span> and <span class="math inline">\(Y\)</span>. And that’s it. We collect those common causes in <span class="math inline">\(X\)</span>. When all of them are measured, we call this <span class="glossary-term">measured confounding</span>. It is the default setup for observational research. Most analyses you will read, and most you will run, assume it, whether or not they say so out loud.</p>
<p>The RHC study fits this setup. Our exposure is receipt of RHC, and our outcome is death within 30 days. Age, sex, diagnosis, blood pressure, heart rate, creatinine, and white blood cell count could all influence both the treatment decision and the patient’s outcome, so we collect the relevant pretreatment information into <span class="math inline">\(X\)</span>.</p>
<p>Our causal assumptions are represented by the SCM</p>
<p><span class="math display">\[
\begin{aligned}
X&amp;\leftarrow f_X(\epsilon_X),\\
A&amp;\leftarrow f_A(X,\epsilon_A),\\
Y&amp;\leftarrow f_Y(X,A,\epsilon_Y),
\end{aligned}
\]</span></p>
<p>with independent noise terms. As a reminder of what this commits us to: the variability in <span class="math inline">\(A\)</span> and <span class="math inline">\(Y\)</span> that <span class="math inline">\(X\)</span> does not explain is independent, so there is no missing variable driving both exposure and outcome. And <span class="math inline">\(X\)</span> is generated before <span class="math inline">\(A\)</span> and <span class="math inline">\(Y\)</span>, not after. Collecting lots of variables to put in <span class="math inline">\(X\)</span> does not, by itself, guarantee either of these two things holds.</p>
<p>The corresponding causal graph is</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/03a-measured-confounding.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="The measured-confounding causal graph. X points to A and Y, and A points to Y." width="620"></p>
</figure>
</div>
<p>For an intervention on <span class="math inline">\(A\)</span> with value <span class="math inline">\(a\)</span>, the potential-outcome assignments are</p>
<p><span class="math display">\[
\begin{aligned}
X(a)&amp;\leftarrow f_X(\epsilon_X),\\
A(a)&amp;\leftarrow f_A(X(a),\epsilon_A),\\
Y(a)&amp;\leftarrow f_Y(X(a),a,\epsilon_Y).
\end{aligned}
\]</span></p>
<p>Their SWIG is</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/03a-measured-confounding-swig.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="The unsimplified measured-confounding SWIG. X(a) points to A(a) and Y(a). Fixed a points to Y(a). The random A(a) and fixed a are separate nearby circles." width="620"></p>
</figure>
</div>
<p>For binary treatment <span class="math inline">\(A\)</span>, a common causal quantity is the average treatment effect:</p>
<p><span class="math display">\[
\operatorname{ATE}=E\left[Y(1)\right]-E\left[Y(0)\right].
\]</span></p>
<p>For RHC, it compares the risk of death if everyone received RHC with the risk if everyone did not. Because <span class="math inline">\(Y\)</span> is binary, <span class="math inline">\(E\left[Y(a)\right]=P\{Y(a)=1\}\)</span>. We can also compare these risks using the causal relative risk,</p>
<p><span class="math display">\[
\frac{E\left[Y(1)\right]}{E\left[Y(0)\right]},
\]</span></p>
<p>or the causal odds ratio,</p>
<p><span class="math display">\[
\frac{E\left[Y(1)\right]/[1-E\left[Y(1)\right]]}
{E\left[Y(0)\right]/[1-E\left[Y(0)\right]]}.
\]</span></p>
<p>The ratios require their denominators to be nonzero, and the odds must be defined. All three comparisons can be constructed from the two means <span class="math inline">\(E\left[Y(1)\right]\)</span> and <span class="math inline">\(E\left[Y(0)\right]\)</span>. So let us identify <span class="math inline">\(E\left[Y(a)\right]\)</span> for a general intervention value <span class="math inline">\(a\)</span>.</p>
</section>
<section id="identification" class="level2">
<h2 class="anchored" data-anchor-id="identification">Identification</h2>
<p>Our task is to rewrite <span class="math inline">\(E\left[Y(a)\right]\)</span> in terms of the observed-data distribution. We make good use of our three rules: causal irrelevance, the global Markov property, and consistency.</p>
<p>First, causal irrelevance. Neither <span class="math inline">\(X(a)\)</span> nor <span class="math inline">\(A(a)\)</span> is a descendant of the fixed intervention value <span class="math inline">\(a\)</span> in the SWIG. Therefore,</p>
<p><span class="math display">\[
X(a)=X,\qquad A(a)=A.
\]</span></p>
<p>After applying causal irrelevance, the assignments become</p>
<p><span class="math display">\[
\begin{aligned}
X&amp;\leftarrow f_X(\epsilon_X),\\
A&amp;\leftarrow f_A(X,\epsilon_A),\\
Y(a)&amp;\leftarrow f_Y(X,a,\epsilon_Y).
\end{aligned}
\]</span></p>
<p>The simplified SWIG is</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/03a-measured-confounding-swig-simplified.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="The simplified measured-confounding SWIG. X points to A and Y(a), and fixed a points to Y(a)." width="620"></p>
</figure>
</div>
<p>Second, global Markov property. The path <span class="math inline">\(A\leftarrow X\to Y(a)\)</span> is blocked when we condition on <span class="math inline">\(X\)</span>. Hence,</p>
<p><span class="math display">\[
A\mathrel{\perp\!\!\!\perp}Y(a)\mid X.
\]</span></p>
<p>This relationship is called <span class="glossary-term" data-bs-toggle="tooltip" data-bs-title="The independence of a potential outcome and the original treatment conditional on baseline variables: $A\mathrel{\perp\!\!\!\perp}Y(a)\mid X$." tabindex="0">conditional exchangeability</span>. Notice that we never had to assume it. It comes for free from the SCM.</p>
<p>This means <span class="math inline">\(A\)</span> got no extra information about <span class="math inline">\(Y(a)\)</span>, beyond what is already known from <span class="math inline">\(X\)</span>. In particular, <span class="math inline">\(A\)</span> does not change the conditional mean:</p>
<p><span class="math display">\[
E\left[Y(a)\mid X\right]=E\left[Y(a)\mid X,A\right].
\]</span></p>
<p>Third, consistency. It tells us that <span class="math inline">\(Y(a)=Y\)</span> whenever <span class="math inline">\(A=a\)</span>. Our last expression has <span class="math inline">\(Y(a)\)</span> inside the expectation and <span class="math inline">\(A\)</span> in the conditioning information. We can pick <span class="math inline">\(A\)</span> to take any value we want and leave the conditional mean untouched. It behooves us to let <span class="math inline">\(A\)</span> take the value <span class="math inline">\(a\)</span>:</p>
<p><span class="math display">\[
E\left[Y(a)\mid X\right]=E\left[Y(a)\mid X,A=a\right].
\]</span></p>
<p>Now consistency lets us make the swap. We are conditioning on <span class="math inline">\(A=a\)</span>, which is exactly the event where <span class="math inline">\(Y(a)=Y\)</span>. So, we swap out <span class="math inline">\(Y(a)\)</span> for <span class="math inline">\(Y\)</span>:</p>
<p><span class="math display">\[
E\left[Y(a)\mid X,A=a\right]=E\left[Y\mid X,A=a\right].
\]</span></p>
<p>Combining the two steps gives</p>
<p><span class="math display">\[
E\left[Y(a)\mid X\right]=E\left[Y\mid X,A=a\right].
\]</span></p>
<p>The left side concerns a potential outcome. The right side uses only original variables, so it is a feature of the observed-data distribution.</p>
<p>There is a small aside we need to make. We need <span class="math inline">\(E\left[Y\mid X,A=a\right]\)</span> to be defined. This relates to the positivity condition we saw for randomized trials, but now it is conditional on <span class="math inline">\(X\)</span>. In practice, it means that for patients with similar values of <span class="math inline">\(X\)</span>, there is a positive chance of getting a treatment close to <span class="math inline">\(a\)</span>. It does not follow direcly from the SCM, so it is a condition we have to add.</p>
<p>But we have to remember what we were after. It was <span class="math inline">\(E\left[Y(a)\right]\)</span>, not <span class="math inline">\(E\left[Y(a)\mid X\right]\)</span>. Fortunately, we have a standard probability trick for getting from one to the other, the law of iterated expectations. Averaging over the distribution of <span class="math inline">\(X\)</span> gives us</p>
<p><span class="math display">\[
E\left[Y(a)\right]=E\big[E\left[Y(a)\mid X\right]\big].
\]</span></p>
<p>Substitute the expression we just obtained:</p>
<p><span class="math display">\[
E\left[Y(a)\right]=E\big[E\left[Y\mid X,A=a\right]\big].
\]</span></p>
<p><em>Done.</em> The outer expectation averages over the distribution of <span class="math inline">\(X\)</span>.</p>
<div class="proposition-box">
<p><strong>Identification under measured confounding.</strong> Assume the SCM above. Then,</p>
<p><span class="math display">\[
E\left[Y(a)\right]=E\big[E\left[Y\mid X,A=a\right]\big],
\]</span> whenever the conditional expectations are defined.</p>
</div>
<p>This expression is often referred to as the <em>g-formula</em> for this setting.</p>
<p>The formula applies to any intervention value <span class="math inline">\(a\)</span> for which the relevant conditional means are defined. For a binary treatment, choosing <span class="math inline">\(a=1\)</span> and <span class="math inline">\(a=0\)</span> gives</p>
<p><span class="math display">\[
E\left[Y(1)\right]
=
E\left[E\left[Y\mid X,A=1\right]\right],
\]</span></p>
<p>and</p>
<p><span class="math display">\[
E\left[Y(0)\right]
=
E\left[E\left[Y\mid X,A=0\right]\right].
\]</span></p>
<p>These identify the two means needed to calculate the ATE and, for a binary outcome, the causal relative risk and causal odds ratio.</p>
</section>
<section id="estimating-the-conditional-mean" class="level2">
<h2 class="anchored" data-anchor-id="estimating-the-conditional-mean">Estimating the conditional mean</h2>
<p>Identification tells us that <span class="math inline">\(E\{Y(a)\}\)</span> can be written using only the distribution of the data we actually observe. No potential outcomes appear on the right-hand side. But we do not know that distribution; all we have is a sample. So the next question is one of estimation. <em>How do we recover the pieces of that expression from data?</em></p>
<p>There are two pieces to estimate, one nested inside the other. Let’s start with the inner one. It will help to give it a name. Define</p>
<p><span class="math display">\[\mu(X,A)=E\left[Y\mid X,A\right].\]</span></p>
<p>This is just a regression function. We hand it a patient’s covariates and a treatment, and it hands back the expected outcome. The inner piece of our formula is this same function with <span class="math inline">\(A\)</span> set to a particular value,</p>
<p><span class="math display">\[\mu(X,a)=E\left[Y\mid X,A=a\right].\]</span></p>
<p>Notice what the notation is doing. The function <span class="math inline">\(\mu\)</span> is something we can learn once, from all of the data. Then <span class="math inline">\(a\)</span> is a number we plug in. After that, <span class="math inline">\(\mu(X,a)\)</span> is random only because <span class="math inline">\(X\)</span> is. That will matter when we get to the outer piece.</p>
<p>So estimating the inner piece means fitting a regression of <span class="math inline">\(Y\)</span> on <span class="math inline">\(X\)</span> and <span class="math inline">\(A\)</span>, which gives us some estimate <span class="math inline">\(\hat\mu(X,A)\)</span>.</p>
<p>Let us make this operation concrete before averaging anything.</p>
<section id="subgroup-means" class="level3">
<h3 class="anchored" data-anchor-id="subgroup-means">Subgroup means</h3>
<div class="example-intro">
<p><span class="example-label">Example: Wildfire smoke and asthma</span></p>
<p>Earlier, we generated a fake dataset in which <span class="math inline">\(X\)</span> indicates unhealthy wildfire smoke, <span class="math inline">\(A\)</span> indicates staying indoors, and <span class="math inline">\(Y\)</span> indicates asthma symptoms. Return to those 10,000 generated observations. Assume the people in our dataset are independent and identically distributed (i.i.d.).</p>
</div>
<p>Here are the numbers of people with each combination of <span class="math inline">\(X\)</span> and <span class="math inline">\(A\)</span>, and the numbers among them with <span class="math inline">\(Y=1\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">X</th>
<th style="text-align: right;">A</th>
<th style="text-align: right;">People</th>
<th style="text-align: right;">People with Y = 1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3038</td>
<td style="text-align: right;">921</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1998</td>
<td style="text-align: right;">389</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1944</td>
<td style="text-align: right;">962</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3020</td>
<td style="text-align: right;">1182</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Let us estimate the conditional mean <span class="math inline">\(\mu(X,A)\)</span>. Since <span class="math inline">\(X\)</span> and <span class="math inline">\(A\)</span> are binary, we need to do this for just four combinations. For each combination, the sample mean of the binary outcome is the proportion with <span class="math inline">\(Y=1\)</span>:</p>
<p><span class="math display">\[
\hat\mu(x,a)
=\frac{\text{number of people with }X=x,\ A=a,\ Y=1}
{\text{number of people with }X=x,\ A=a}.
\]</span></p>
<p>Using the counts above gives</p>
<p><span class="math display">\[
\begin{aligned}
\hat\mu(0,0)&amp;=\frac{921}{3038}\approx 0.303,\\
\hat\mu(0,1)&amp;=\frac{389}{1998}\approx 0.195,\\
\hat\mu(1,0)&amp;=\frac{962}{1944}\approx 0.495,\\
\hat\mu(1,1)&amp;=\frac{1182}{3020}\approx 0.391.
\end{aligned}
\]</span></p>
<p>We now have <span class="math inline">\(\hat\mu(x,a)\)</span> for every possible combination. Recall why we wanted this function. Our identification argument gave us</p>
<p><span class="math display">\[
E\left[Y(a)\mid X\right]
=
E\left[Y\mid X,A=a\right]
=
\mu(X,a).
\]</span></p>
<p>So, by estimating <span class="math inline">\(\mu(X,a)\)</span>, we are estimating the expected potential outcome under intervention value <span class="math inline">\(a\)</span> for people with that value of <span class="math inline">\(X\)</span>. Since <span class="math inline">\(Y\)</span> is binary, this is their probability of asthma symptoms under that intervention.</p>
<p>For someone without unhealthy wildfire smoke, plug in <span class="math inline">\(X=0\)</span> and each treatment value:</p>
<p><span class="math display">\[
\hat\mu(0,1)=0.195,
\qquad
\hat\mu(0,0)=0.303.
\]</span></p>
<p>Under our SCM, we estimate that 19.5% of people in this group would have asthma symptoms if we intervened to have them stay indoors, compared with 30.3% if we intervened to have them not stay indoors.</p>
<p>For someone with unhealthy wildfire smoke (<span class="math inline">\(X=1\)</span>), the same operation gives</p>
<p><span class="math display">\[
\hat\mu(1,1)=0.391,
\qquad
\hat\mu(1,0)=0.495.
\]</span></p>
<p>We estimate that 39.1% of people in this group would have asthma symptoms under the stay-indoors intervention, compared with 49.5% under the do-not-stay-indoors intervention.</p>
<p>In each case, we keep <span class="math inline">\(X\)</span> fixed and change the treatment input. This gives us both <span class="math inline">\(\hat\mu(X,1)\)</span> and <span class="math inline">\(\hat\mu(X,0)\)</span> for every person, regardless of their recorded treatment.</p>
<p>Here are the fitted values for four people, one with each combination of <span class="math inline">\(X\)</span> and <span class="math inline">\(A\)</span>.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;"><span class="math inline">\(X\)</span></th>
<th style="text-align: right;">Recorded <span class="math inline">\(A\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\hat\mu(X,A)\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\hat\mu(X,1)\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\hat\mu(X,0)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.303</td>
<td style="text-align: right;">0.195</td>
<td style="text-align: right;">0.303</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.195</td>
<td style="text-align: right;">0.195</td>
<td style="text-align: right;">0.303</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.495</td>
<td style="text-align: right;">0.391</td>
<td style="text-align: right;">0.495</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.391</td>
<td style="text-align: right;">0.391</td>
<td style="text-align: right;">0.495</td>
</tr>
</tbody>
</table>
<p>The fitted value <span class="math inline">\(\hat\mu(X,A)\)</span> uses the recorded treatment. The other two columns use the same recorded <span class="math inline">\(X\)</span> but substitute <span class="math inline">\(1\)</span> or <span class="math inline">\(0\)</span> for the treatment input. People with the same <span class="math inline">\(X\)</span> therefore receive the same pair of predictions, even when their recorded treatments differ.</p>
</section>
<section id="linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="linear-regression">Linear regression</h3>
<p>That was straightforward because there were only four combinations of <span class="math inline">\(X\)</span> and <span class="math inline">\(A\)</span>. We could estimate a separate mean for each one without imposing a model relating those means. With more covariates, or continuous covariates, we may have few or no observations at a particular combination. A regression model lets us estimate the conditional mean by sharing information across different covariate values.</p>
<div class="example-intro">
<p><span class="example-label">Example: Smoking and birth weight</span></p>
<p>The birth-weight dataset contains 189 births recorded at Baystate Medical Center in 1986. Let <span class="math inline">\(A\)</span> indicate smoking during pregnancy, <span class="math inline">\(X\)</span> be maternal weight at the last menstrual period in pounds, and <span class="math inline">\(Y\)</span> be infant birth weight in grams. These are real observations, rather than generated data. <a href="https://www.stat.math.ethz.ch/R-manual/R-devel/library/MASS/html/birthwt.html">Dataset documentation</a></p>
</div>
<p>For this illustration, assume the observations are i.i.d. and use the measured-confounding SCM with <span class="math inline">\(X\)</span> as the baseline covariate.</p>
<p>We fit a linear regression to estimate the conditional mean:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>birthwt <span class="ot">&lt;-</span> <span class="cf">if</span> (<span class="fu">file.exists</span>(<span class="st">"data/birthwt.csv"</span>)) {</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read.csv</span>(<span class="st">"data/birthwt.csv"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  MASS<span class="sc">::</span>birthwt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>birthwt_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(bwt <span class="sc">~</span> lwt <span class="sc">+</span> smoke, <span class="at">data =</span> birthwt)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The fitted equation is</p>
<p><span class="math display">\[
\hat\mu(X,A)=2501.125+4.237X-272.081A.
\]</span></p>
<p>Consider a mother whose recorded weight is 120 pounds. Plug in that weight and each smoking value:</p>
<p><span class="math display">\[
\begin{aligned}
\hat\mu(120,1)
&amp;=2501.125+4.237(120)-272.081(1)
\approx2737.5,\\
\hat\mu(120,0)
&amp;=2501.125+4.237(120)-272.081(0)
\approx3009.6.
\end{aligned}
\]</span></p>
<p>Recall that our identification argument gives</p>
<p><span class="math display">\[
E\left[Y(a)\mid X\right]=\mu(X,a).
\]</span></p>
<p>So for mothers whose baseline weight was 120 pounds, we estimate a mean infant birth weight of 2737.5 grams under an intervention in which they smoke during pregnancy, compared with 3009.5 grams under an intervention in which they do not smoke. Under our SCM, smoking therefore lowers mean birth weight for this mother by an estimated 272.1 grams.</p>
<p>The R function <code>predict()</code> performs the same substitution. For a mother weighing 120 pounds, supply that weight with smoking set to <span class="math inline">\(1\)</span> or <span class="math inline">\(0\)</span>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>mother_120 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">lwt =</span> <span class="fu">c</span>(<span class="dv">120</span>, <span class="dv">120</span>),</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">smoke =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(birthwt_fit, <span class="at">newdata =</span> mother_120)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2 
2737.453 3009.534 </code></pre>
</div>
</div>
<p>The first prediction is 2737.5 grams for smoking during pregnancy (<span class="math inline">\(A=1\)</span>). The second is 3009.5 grams for not smoking during pregnancy (<span class="math inline">\(A=0\)</span>). These are the same fitted conditional means we calculated by hand.</p>
<p>We can perform these same calculations for different baseline weights. Using the R function <code>predict()</code>, we make two copies of the data, retain each mother’s recorded weight, and set smoking to a different value in each copy:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>birthwt_under_1 <span class="ot">&lt;-</span> birthwt</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>birthwt_under_1<span class="sc">$</span>smoke <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>birthwt_under_0 <span class="ot">&lt;-</span> birthwt</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>birthwt_under_0<span class="sc">$</span>smoke <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>birthwt_fitted <span class="ot">&lt;-</span> <span class="fu">predict</span>(birthwt_fit, <span class="at">newdata =</span> birthwt)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>birthwt_pred_1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(birthwt_fit, <span class="at">newdata =</span> birthwt_under_1)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>birthwt_pred_0 <span class="ot">&lt;-</span> <span class="fu">predict</span>(birthwt_fit, <span class="at">newdata =</span> birthwt_under_0)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Here are four actual observations, selected to show different weights and both recorded smoking values:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">X</th>
<th style="text-align: right;">A</th>
<th style="text-align: right;">Y</th>
<th style="text-align: right;"><span class="math inline">\(\hat\mu(X,A)\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\hat\mu(X,1)\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\hat\mu(X,0)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">182</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2523</td>
<td style="text-align: right;">3272.2</td>
<td style="text-align: right;">3000.1</td>
<td style="text-align: right;">3272.2</td>
</tr>
<tr class="even">
<td style="text-align: right;">155</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2551</td>
<td style="text-align: right;">3157.8</td>
<td style="text-align: right;">2885.7</td>
<td style="text-align: right;">3157.8</td>
</tr>
<tr class="odd">
<td style="text-align: right;">105</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2557</td>
<td style="text-align: right;">2673.9</td>
<td style="text-align: right;">2673.9</td>
<td style="text-align: right;">2946.0</td>
</tr>
<tr class="even">
<td style="text-align: right;">108</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2594</td>
<td style="text-align: right;">2686.6</td>
<td style="text-align: right;">2686.6</td>
<td style="text-align: right;">2958.7</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The first prediction uses the recorded smoking value. The next two keep the same maternal weight and substitute smoking values <span class="math inline">\(1\)</span> and <span class="math inline">\(0\)</span>.</p>
<p>A more elaborate regression might include several baseline variables, nonlinear terms, or treatment interactions. The prediction operation remains the same.</p>
</section>
<section id="logistic-regression" class="level3">
<h3 class="anchored" data-anchor-id="logistic-regression">Logistic regression</h3>
<div class="example-intro">
<p><span class="example-label">Example: Smoking and low birth weight</span></p>
<p>Use the same birth-weight dataset, but now let <span class="math inline">\(Y\)</span> indicate low birth weight: <span class="math inline">\(Y=1\)</span> if the infant weighs less than 2,500 grams, and <span class="math inline">\(Y=0\)</span> otherwise. This is the variable <code>low</code> in our dataset. As before, <span class="math inline">\(X\)</span> is maternal weight in pounds, and <span class="math inline">\(A=1\)</span> means smoking during pregnancy while <span class="math inline">\(A=0\)</span> means not smoking.</p>
</div>
<p>Since <span class="math inline">\(Y\)</span> is binary, its conditional mean is a probability:</p>
<p><span class="math display">\[
\mu(x,a)=E\left[Y\mid X=x,A=a\right]
=P(Y=1\mid X=x,A=a).
\]</span></p>
<p>We estimate this function using logistic regression:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>birthwt_logistic_fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  low <span class="sc">~</span> lwt <span class="sc">+</span> smoke,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> birthwt</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>There is one extra step compared with linear regression. Logistic regression models the log odds of the conditional mean:</p>
<p><span class="math display">\[
\operatorname{logit}\{\mu(x,a)\}
=\log\left[\frac{\mu(x,a)}{1-\mu(x,a)}\right]
=\beta_0+\beta_Xx+\beta_Aa.
\]</span></p>
<p>The fitted equation is</p>
<p><span class="math display">\[
\operatorname{logit}\{\hat\mu(x,a)\}
\approx0.62-1.33\frac{x}{100}+0.68a.
\]</span></p>
<p>Plugging in <span class="math inline">\(x\)</span> and <span class="math inline">\(a\)</span> gives estimated log odds. We must transform back to a probability to obtain <span class="math inline">\(\hat\mu(x,a)\)</span>.</p>
<p>For a mother weighing 120 pounds, under smoking value <span class="math inline">\(a=1\)</span>, the fitted log odds are approximately</p>
<p><span class="math display">\[
0.62-1.33\frac{120}{100}+0.68(1)\approx-0.30.
\]</span></p>
<p>Transforming back gives</p>
<p><span class="math display">\[
\hat\mu(120,1)
\approx\frac{\exp(-0.30)}{1+\exp(-0.30)}
\approx0.43.
\]</span></p>
<p>Under smoking value <span class="math inline">\(a=0\)</span>, the fitted log odds are approximately</p>
<p><span class="math display">\[
0.62-1.33\frac{120}{100}+0.68(0)\approx-0.98.
\]</span></p>
<p>Transforming back gives</p>
<p><span class="math display">\[
\hat\mu(120,0)
\approx\frac{\exp(-0.98)}{1+\exp(-0.98)}
\approx0.27.
\]</span></p>
<p>Recall the connection to our causal question:</p>
<p><span class="math display">\[
E\left[Y(a)\mid X\right]=\mu(X,a).
\]</span></p>
<p>Under our working causal model, we estimate that 42.5% of infants would have low birth weight if mothers weighing 120 pounds smoked during pregnancy, compared with 27.4% if they did not smoke.</p>
<p>The R function <code>predict()</code> performs the same calculation. Supply the same weight with smoking set to <span class="math inline">\(1\)</span> or <span class="math inline">\(0\)</span>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>mother_120 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">lwt =</span> <span class="fu">c</span>(<span class="dv">120</span>, <span class="dv">120</span>),</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">smoke =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">predict</span>(birthwt_logistic_fit, <span class="at">newdata =</span> mother_120), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    1     2 
-0.30 -0.98 </code></pre>
</div>
</div>
<p>By default, this returns fitted log odds: approximately <span class="math inline">\(-0.30\)</span> and <span class="math inline">\(-0.98\)</span>. To obtain the estimated conditional means, ask for predictions on the response scale:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">predict</span>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  birthwt_logistic_fit,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">newdata =</span> mother_120,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"response"</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   1    2 
0.43 0.27 </code></pre>
</div>
</div>
<p>This returns <span class="math inline">\(0.43\)</span> and <span class="math inline">\(0.27\)</span>. The argument <code>type = "response"</code> performs the transformation from log odds back to probabilities.</p>
<p>We can now do this for everyone, using the copies of the data with smoking set to <span class="math inline">\(1\)</span> and <span class="math inline">\(0\)</span>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>birthwt_risk_1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  birthwt_logistic_fit,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">newdata =</span> birthwt_under_1,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"response"</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>birthwt_risk_0 <span class="ot">&lt;-</span> <span class="fu">predict</span>(</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  birthwt_logistic_fit,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">newdata =</span> birthwt_under_0,</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"response"</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>These estimate <span class="math inline">\(\mu(X,1)\)</span> and <span class="math inline">\(\mu(X,0)\)</span> for every mother. We retain each mother’s recorded weight and change only the smoking input. The additional operation is transforming the fitted log odds back to the conditional mean.</p>
<p>The SCM justified the identification formula. The regression is an additional choice about how to estimate its conditional mean. Here, we assume a linear relationship on the log-odds scale and no treatment interaction.</p>
<p>This is the same logistic regression you may have used before. The only new step is what we report. Instead of odds or odds ratios, we use the fitted model to predict on the probability scale. That is what we need here, because <span class="math inline">\(\mu(X,a)\)</span> is the probability of low birth weight at a given value of <span class="math inline">\(X\)</span> and treatment <span class="math inline">\(a\)</span>.</p>
</section>
<section id="general-case" class="level3">
<h3 class="anchored" data-anchor-id="general-case">General case</h3>
<p>Nothing about this idea is special to linear or logistic regression. Poisson regression, other generalized linear models, and generalized estimating equations (GEE) all do the same job: they model the conditional mean of <span class="math inline">\(Y\)</span> given <span class="math inline">\(X\)</span> and <span class="math inline">\(A\)</span>.</p>
<p>The recipe is the same each time. Regress <span class="math inline">\(Y\)</span> on <span class="math inline">\(X\)</span> and <span class="math inline">\(A\)</span>. Then use the fitted model to predict the conditional mean for each person, using their recorded <span class="math inline">\(X\)</span> and each intervention value <span class="math inline">\(a\)</span> we care about. If the model uses a link function, transform back to the outcome scale, just as we did with logistic regression.</p>
<p>There is plenty of room for creativity in how we model this mean. We can include nonlinear relationships and interactions. But the task never changes: we are estimating <span class="math inline">\(\mu(X,a)\)</span>. Once we have those predictions for everyone, we can turn to the outer expectation.</p>
</section>
</section>
<section id="estimating-the-outer-expectation" class="level2">
<h2 class="anchored" data-anchor-id="estimating-the-outer-expectation">Estimating the outer expectation</h2>
<p>Return to the expression we identified:</p>
<p><span class="math display">\[
E\left[Y(a)\right]=E\left[\mu(X,a)\right].
\]</span></p>
<p>The outer expectation is the mean of some function of <span class="math inline">\(X\)</span>. Notice that <span class="math inline">\(a\)</span> is a fixed number. That means <span class="math inline">\(\mu(X,a)\)</span> varies only when <span class="math inline">\(X\)</span> does. The outer expectation averages that function over the distribution of <span class="math inline">\(X\)</span>.</p>
<p>We could dream up more elaborate ways to estimate this mean. But there is something we already know how to do: <em>take a sample mean.</em></p>
<p>First, some notation. For each unit <span class="math inline">\(i\)</span>, let <span class="math inline">\(x_i\)</span> be the covariate values we recorded for that unit. These are the observed values of <span class="math inline">\(X\)</span>, and they are the numbers we will actually plug in.</p>
<p>We do not know <span class="math inline">\(\mu\)</span>, but we have already estimated it. So we start by swapping the fitted function in for the true one:</p>
<p><span class="math display">\[E\left[Y(a)\right]=E\left[\mu(X,a)\right]\approx E\left[\hat\mu(X,a)\right].\]</span></p>
<p>This still averages over the distribution of <span class="math inline">\(X\)</span>, which we do not have. What we do have is a sample. Because we assumed i.i.d. sampling, the observed <span class="math inline">\(x_1,\ldots,x_n\)</span> are draws from that distribution, so we can estimate this expectation with a sample mean. We evaluate <span class="math inline">\(\hat\mu\)</span> at each <span class="math inline">\(x_i\)</span>, add up those values, and divide by <span class="math inline">\(n\)</span>:</p>
<p><span class="math display">\[E\left[\hat\mu(X,a)\right]\approx\frac{1}{n}\sum_{i=1}^n \hat\mu(x_i,a).\]</span></p>
<p>Putting the two approximations together gives our estimate,</p>
<p><span class="math display">\[E\left[Y(a)\right]\approx\frac{1}{n}\sum_{i=1}^n \hat\mu(x_i,a).\]</span></p>
<p>Notice that the sum runs over all <span class="math inline">\(n\)</span> units, whether or not they actually received <span class="math inline">\(a\)</span>. For <span class="math inline">\(a=1\)</span>, this means averaging the <span class="math inline">\(\hat\mu(X,1)\)</span> values; for <span class="math inline">\(a=0\)</span>, the <span class="math inline">\(\hat\mu(X,0)\)</span> values.</p>
<p>Let’s return to our three examples.</p>
<p>Return first to the generated wildfire-smoke and asthma dataset. For each of the 5,036 people with <span class="math inline">\(X=0\)</span>, we calculated <span class="math inline">\(\hat\mu(X,1)=0.195\)</span>. For each of the 4,964 people with <span class="math inline">\(X=1\)</span>, we calculated <span class="math inline">\(\hat\mu(X,1)=0.391\)</span>. The sample mean of these 10,000 values is</p>
<p><span class="math display">\[
E\left[Y(1)\right]
\approx\frac{5036(0.195)+4964(0.391)}{10000}
\approx0.29.
\]</span></p>
<p>Under not staying indoors, we calculated <span class="math inline">\(\hat\mu(X,0)=0.303\)</span> for each of the 5,036 people with <span class="math inline">\(X=0\)</span>, and <span class="math inline">\(\hat\mu(X,0)=0.495\)</span> for each of the 4,964 people with <span class="math inline">\(X=1\)</span>. The sample mean of these 10,000 values is</p>
<p><span class="math display">\[
E\left[Y(0)\right]
\approx\frac{5036(0.303)+4964(0.495)}{10000}
\approx0.40.
\]</span></p>
<p>You might have seen this before as <strong>direct standardization</strong>: averaging the conditional means using the same baseline distribution for each treatment value.</p>
<p>Now bring the two risks together. Their difference gives the ATE:</p>
<p><span class="math display">\[
\operatorname{ATE}=E\left[Y(1)\right]-E\left[Y(0)\right]\approx-0.11.
\]</span></p>
<p>Under our causal model, staying indoors rather than not staying indoors lowers the risk of asthma symptoms by an estimated 10.6 percentage points. We calculate the contrasts using the fitted values before rounding.</p>
<p>We can also compare the risks as a ratio:</p>
<p><span class="math display">\[
\text{Causal relative risk}
=\frac{E\left[Y(1)\right]}{E\left[Y(0)\right]}
\approx0.73.
\]</span></p>
<p>The risk under staying indoors is about 0.73 times the risk under not staying indoors. To compare odds instead, convert each risk to odds and take their ratio:</p>
<p><span class="math display">\[
\text{Causal odds ratio}
=\frac{E\left[Y(1)\right]/\left(1-E\left[Y(1)\right]\right)}
{E\left[Y(0)\right]/\left(1-E\left[Y(0)\right]\right)}
\approx0.62.
\]</span></p>
<p>The odds of asthma symptoms under staying indoors are about 0.62 times the odds under not staying indoors. These are three ways to compare the same two intervention risks.</p>
<p>Now return to the linear-regression birth-weight example. The function <span class="math inline">\(\hat\mu(X,a)\)</span> came from a fitted line, but the outer operation is unchanged. Average the predictions over all 189 mothers:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>birthwt_mean_1 <span class="ot">&lt;-</span> <span class="fu">mean</span>(birthwt_pred_1)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>birthwt_mean_0 <span class="ot">&lt;-</span> <span class="fu">mean</span>(birthwt_pred_0)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>birthwt_ate <span class="ot">&lt;-</span> birthwt_mean_1 <span class="sc">-</span> birthwt_mean_0</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This gives</p>
<p><span class="math display">\[
\begin{aligned}
E\left[Y(1)\right]&amp;\approx2779.0\text{ grams},\\
E\left[Y(0)\right]&amp;\approx3051.1\text{ grams}.
\end{aligned}
\]</span></p>
<p>The estimated average treatment effect is therefore</p>
<p><span class="math display">\[
\operatorname{ATE}
=E\left[Y(1)\right]-E\left[Y(0)\right]
\approx-272.1\text{ grams}.
\]</span></p>
<p>Under the working causal model and fitted regression, we estimate that smoking during pregnancy rather than not smoking would lower mean infant birth weight by 272.1 grams.</p>
<p>Notice that <span class="math inline">\(-272.1\)</span> grams is also the coefficient on <span class="math inline">\(A\)</span> in our fitted regression. This works because we used linear regression without treatment interactions: changing <span class="math inline">\(A\)</span> from <span class="math inline">\(0\)</span> to <span class="math inline">\(1\)</span> changes everyone’s predicted outcome by the same amount, so averaging those differences gives that coefficient. Do not carry this shortcut over to every regression.</p>
<p>Finally, return to the logistic-regression example. We already transformed the fitted log odds to probabilities, giving us <span class="math inline">\(\hat\mu(X,a)\)</span>. The outer expectation is the mean of these probabilities, so average them over all 189 mothers:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>low_risk_1 <span class="ot">&lt;-</span> <span class="fu">mean</span>(birthwt_risk_1)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>low_risk_0 <span class="ot">&lt;-</span> <span class="fu">mean</span>(birthwt_risk_0)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>low_ate <span class="ot">&lt;-</span> low_risk_1 <span class="sc">-</span> low_risk_0</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>low_causal_rr <span class="ot">&lt;-</span> low_risk_1 <span class="sc">/</span> low_risk_0</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>low_causal_or <span class="ot">&lt;-</span> (low_risk_1 <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> low_risk_1)) <span class="sc">/</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  (low_risk_0 <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> low_risk_0))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This gives estimated risks of</p>
<p><span class="math display">\[
E\left[Y(1)\right]\approx0.40,
\qquad
E\left[Y(0)\right]\approx0.26.
\]</span></p>
<p>Their difference gives</p>
<p><span class="math display">\[
\operatorname{ATE}
=E\left[Y(1)\right]-E\left[Y(0)\right]
\approx0.14.
\]</span></p>
<p>Under our working causal model, smoking during pregnancy rather than not smoking increases the risk of low birth weight by an estimated 14.3 percentage points. Comparing the risks as a ratio gives</p>
<p><span class="math display">\[
\text{Causal relative risk}
=\frac{E\left[Y(1)\right]}
{E\left[Y(0)\right]}
\approx1.56.
\]</span></p>
<p>The risk under smoking is about 1.56 times the risk under not smoking. Converting the risks to odds gives</p>
<p><span class="math display">\[
\text{Causal odds ratio}
=\frac{E\left[Y(1)\right]/\left(1-E\left[Y(1)\right]\right)}
{E\left[Y(0)\right]/\left(1-E\left[Y(0)\right]\right)}
\approx1.93.
\]</span></p>
<p>The odds of low birth weight under smoking are about 1.93 times the odds under not smoking. Again, all three comparisons use the same two risks, calculated from the predictions.</p>
<p>For treatments with other possible values, we can repeat the same prediction-and-averaging operation at the intervention values we want to compare. For example, subtracting the estimated mean under <span class="math inline">\(a\)</span> from the estimated mean under <span class="math inline">\(a'\)</span> estimates <span class="math inline">\(E\left[Y(a')\right]-E\left[Y(a)\right]\)</span>.</p>
<p>We fitted one outcome regression, predicted for everyone under each treatment value, and averaged those predictions. Then we combined those averages to answer our causal question. Bob’s our uncle.</p>
</section>
<section id="beyond-binary-exposures" class="level2">
<h2 class="anchored" data-anchor-id="beyond-binary-exposures">Beyond binary exposures</h2>
<p>Nothing in this procedure requires the exposure to be binary. We can predict and average at each intervention value <span class="math inline">\(a\)</span> of interest, then compare the resulting means with the mean under a reference value.</p>
<div class="example-intro">
<p><span class="example-label">Example: Blood pressure and the RHC decision</span></p>
<p>Return to the RHC data, but change the question. Let <span class="math inline">\(A\)</span> be mean blood pressure in mmHg and <span class="math inline">\(Y\)</span> indicate receiving RHC. Collect age, diagnosis, and creatinine in <span class="math inline">\(X\)</span>.</p>
<p>For this worked example, assume an i.i.d. sample and the measured-confounding SCM with arrows <span class="math inline">\(X\to A\)</span>, <span class="math inline">\(X\to Y\)</span>, and <span class="math inline">\(A\to Y\)</span>, and independent noise terms. We are treating the covariates as preceding blood pressure and blood pressure as preceding the RHC decision. These are working assumptions; the recorded measurements do not by themselves establish this ordering or that these covariates capture all common causes. The intervention sets blood pressure in this SCM, rather than specifying a particular drug used to change it.</p>
</div>
<p>The conditional mean is now the probability of receiving RHC. Fit a logistic regression with a spline for blood pressure and an interaction with diagnosis:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>rhc_source <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/rhc.csv"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>rhc_bp <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean_blood_pressure =</span> rhc_source<span class="sc">$</span>meanbp1,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">rhc =</span> <span class="fu">as.integer</span>(rhc_source<span class="sc">$</span>swang1 <span class="sc">==</span> <span class="st">"RHC"</span>),</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> rhc_source<span class="sc">$</span>age,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">diagnosis =</span> <span class="fu">factor</span>(rhc_source<span class="sc">$</span>cat1),</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">creatinine =</span> rhc_source<span class="sc">$</span>crea1</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>rhc_bp_fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>  rhc <span class="sc">~</span> splines<span class="sc">::</span><span class="fu">ns</span>(mean_blood_pressure, <span class="at">df =</span> <span class="dv">3</span>) <span class="sc">*</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    diagnosis <span class="sc">+</span> age <span class="sc">+</span> creatinine,</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(),</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> rhc_bp</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The spline allows the relationship to bend, and the interaction allows its shape to differ by diagnosis. We do not need to write out every coefficient to use the fitted function. As before, <code>predict(..., type = "response")</code> gives us <span class="math inline">\(\hat\mu(X,a)\)</span> on the probability scale.</p>
<p>Start with <span class="math inline">\(a=80\)</span> mmHg. Keep everyone’s recorded covariates, set blood pressure to 80, predict, and average:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>rhc_bp_80 <span class="ot">&lt;-</span> rhc_bp</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>rhc_bp_80<span class="sc">$</span>mean_blood_pressure <span class="ot">&lt;-</span> <span class="dv">80</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>rhc_bp_predictions_80 <span class="ot">&lt;-</span> <span class="fu">predict</span>(</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  rhc_bp_fit, <span class="at">newdata =</span> rhc_bp_80, <span class="at">type =</span> <span class="st">"response"</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>rhc_bp_mean_80 <span class="ot">&lt;-</span> <span class="fu">mean</span>(rhc_bp_predictions_80)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This gives <span class="math inline">\(E\left[Y(80)\right]\approx\)</span> 0.35. Under our working model, an estimated 35.0% would receive RHC if we set mean blood pressure to 80 mmHg.</p>
<p>Now repeat that operation for each blood pressure we want to consider:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>mean_rhc_at <span class="ot">&lt;-</span> <span class="cf">function</span>(a) {</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  under_a <span class="ot">&lt;-</span> rhc_bp</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  under_a<span class="sc">$</span>mean_blood_pressure <span class="ot">&lt;-</span> a</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(<span class="fu">predict</span>(rhc_bp_fit, <span class="at">newdata =</span> under_a, <span class="at">type =</span> <span class="st">"response"</span>))</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>blood_pressure_values <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">60</span>, <span class="dv">120</span>, <span class="at">by =</span> <span class="dv">1</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>rhc_bp_curve <span class="ot">&lt;-</span> <span class="fu">vapply</span>(blood_pressure_values, mean_rhc_at, <span class="fu">numeric</span>(<span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Each point estimates <span class="math inline">\(E\left[Y(a)\right]\)</span> at one value of <span class="math inline">\(a\)</span>. Together, they give an estimated mean response curve:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03a-outcome-regression_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" alt="Estimated probability of receiving RHC under interventions setting mean blood pressure between 60 and 120 mmHg, averaging fitted probabilities over the same recorded covariates at each value." width="672"></p>
</figure>
</div>
</div>
</div>
<p>To compare values, choose a reference. Using 80 mmHg, compare 60 and 100 mmHg with that same reference:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>rhc_bp_mean_60 <span class="ot">&lt;-</span> <span class="fu">mean_rhc_at</span>(<span class="dv">60</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>rhc_bp_mean_100 <span class="ot">&lt;-</span> <span class="fu">mean_rhc_at</span>(<span class="dv">100</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>At 60 mmHg, the estimated probability of receiving RHC is 0.42. The difference from the reference is</p>
<p><span class="math display">\[
E\left[Y(60)\right]-E\left[Y(80)\right]
\approx 0.07.
\]</span></p>
<p>That is an estimated change of 6.9 percentage points. The causal relative risk is</p>
<p><span class="math display">\[
\frac{E\left[Y(60)\right]}{E\left[Y(80)\right]}
\approx 1.20.
\]</span></p>
<p>Under our model, the probability of receiving RHC at 60 mmHg is about 1.20 times the probability at 80 mmHg.</p>
<p>At 100 mmHg, the corresponding probability is 0.29. Comparing with 80 mmHg gives</p>
<p><span class="math display">\[
\begin{aligned}
E\left[Y(100)\right]-E\left[Y(80)\right]
&amp;\approx -0.06,\\
\frac{E\left[Y(100)\right]}{E\left[Y(80)\right]}
&amp;\approx 0.84.
\end{aligned}
\]</span></p>
<p>The estimated change is -5.7 percentage points, and the probability is about 0.84 times that at the reference blood pressure. These comparisons use the same people’s covariates at every intervention value.</p>
<p>The same idea works for a count exposure: evaluate the fitted conditional mean at each allowed integer value, average over the sample, and compare with a reference. Binary, count, or continuous, the operation stays the same. The values we choose must still be ones for which we can estimate the relevant conditional means.</p>
<div class="callout callout-style-default callout-note callout-titled" title="The overall idea">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The overall idea
</div>
</div>
<div class="callout-body-container callout-body">
<p>Outcome regression comes down to three steps: regress <span class="math inline">\(Y\)</span> on <span class="math inline">\(X\)</span> and <span class="math inline">\(A\)</span>, predict the conditional mean for everyone at each intervention value <span class="math inline">\(a\)</span>, and average those predictions. Then compare the averages to estimate the causal quantity we care about. The regression model can change, and the exposure need not be binary. The idea stays the same.</p>
</div>
</div>


</section>

</main> <!-- /main -->
<script>
document.addEventListener("DOMContentLoaded", () => {
  document.querySelectorAll('[data-bs-toggle="tooltip"]').forEach((element) => {
    new bootstrap.Tooltip(element, {
      placement: "top",
      trigger: "hover focus"
    });
  });
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./02-exercises.html" class="pagination-link" aria-label="Exercises">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Exercises</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./03-exercises.html" class="pagination-link" aria-label="Exercises">
        <span class="nav-page-text"><span class="chapter-title">Exercises</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>